---
title: "Test"
author: "Roland Koffi & Gerald Miezan"
date: '2022-07-07'
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
```


```{r}
table_prime_pos <- read_excel("RShiny/Dashboard/data/table_jointe_positive.xlsx", sheet = "Feuil2")
table_prime_neg <- read_excel("RShiny/Dashboard/data/table_jointe_negative.xlsx", sheet = "Feuil2")
```


```{r}
head(table_prime_pos)
```

```{r}
head(table_prime_neg)
```

```{r}
table_prime_pos <- table_prime_pos %>% mutate(FAIRE_SINISTRE = case_when(NBSIN == 0 ~ 0, NBSIN != 0 ~ 1))
```


```{r}
donne_entrai <- table_prime_pos %>% filter(ANNEE %in% c(2017,2018))
donnee_test <- table_prime_pos %>% filter(ANNEE == 2019)
```

```{r}
head(donnee_test)
```



```{r}
model_prev_faire_sin <- glm(FAIRE_SINISTRE ~ CODEZONE + TYPEMOTE + CODE_USAGE, family=binomial, data = donne_entrai)
summary(model_prev_faire_sin)
```

```{r}
val_pred <- as.data.frame(predict(model_prev_faire_sin,donnee_test,type = "response"))
tabl_var <- data.frame(y = donnee_test[,33], y_chap = round(val_pred))

```















































































































































































































